<a href="https://colab.research.google.com/github/Ramakant-Tiwari/machine-learning-tuts/blob/main/numpy-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

np.__version__

'1.26.4'

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[1, 2, 3, 4, 5]])

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]])

one_d, two_d, three_d

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3, 4, 5]]),
 array([[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
one_d.shape, one_d.ndim, one_d.dtype, one_d.size, type(one_d)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array
two_d.shape, two_d.ndim, two_d.dtype, two_d.size, type(two_d)

((1, 5), 2, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Attributes of 3-dimensional array
three_d.shape, three_d.ndim, three_d.dtype, three_d.size, type(three_d)

((1, 2, 5), 3, dtype('int64'), 10, numpy.ndarray)

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1 = pd.Series(one_d)
a2 = pd.DataFrame(two_d)
a3 = pd.DataFrame(three_d.reshape(1, 10))

a1, a2, a3

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
    0  1  2  3  4
 0  1  2  3  4  5,
    0  1  2  3  4  5  6  7  8  9
 0  1  2  3  4  5  1  2  3  4  5)

In [ ]:
# Create an array of shape (10, 2) with only ones
a4 = pd.DataFrame(np.random.randint(1, 2, size=(10, 2)))
a4

0  1
0  1  1
1  1  1
2  1  1
3  1  1
4  1  1
5  1  1
6  1  1
7  1  1
8  1  1
9  1  1

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 101, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, size=(7, 2))

array([[5, 0],
       [7, 5],
       [6, 4],
       [6, 7],
       [1, 5],
       [5, 7],
       [6, 0]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((5, 3))

array([[0.82813573, 0.83065704, 0.01583544],
       [0.10520527, 0.3737512 , 0.48538681],
       [0.90424676, 0.57673021, 0.43162835],
       [0.36893215, 0.12276603, 0.46856173],
       [0.48795817, 0.95131649, 0.5628478 ]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a110 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(a110)

array([1, 2, 3, 4, 5, 7, 9])

In [ ]:
# Find the 0'th index of the latest array you created
a110[0]

array([9, 1, 3, 7, 4, 9, 3])

In [ ]:
# Get the first 2 rows of latest array you created
a110[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
a110[:2, :2]

array([[9, 1],
       [5, 3]])

In [ ]:
# Add the two arrays together
np.ones(shape=(1, 10)) + np.ones(shape=(10, 1))

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [ ]:
# Create another array of ones of shape (5, 3)
np.ones(shape=(5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Try add the array of ones and the other most recent array together
# done

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [7]:
# Create another array of ones of shape (3, 5)
import numpy as np
ones = np.ones(shape=(3,5))

In [9]:
# Subtract the new array of ones from the other most recent array
ones, ones - ones

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [10]:
# Multiply the ones array with the latest array
ones, ones * np.zeros(shape=(3, 5))

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [11]:
# Take the latest array to the power of 2 using '**'
ones ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Do the same thing with np.square()
np.square(ones)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Find the mean of the latest array using np.mean()
np.mean(ones)

1.0

In [14]:
# Find the maximum of the latest array using np.max()
np.max(ones)

1.0

In [15]:
# Find the minimum of the latest array using np.min()
np.min(ones)

1.0

In [16]:
# Find the standard deviation of the latest array
np.std(ones)

0.0

In [17]:
# Find the variance of the latest array
np.var(ones)

0.0

In [22]:
# Reshape the latest array to (3, 5, 1)
ones.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [24]:
# Transpose the latest array
ones.T, ones

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

What does the transpose do?

In [25]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1, a2 = np.random.randint(0, 10, size=(3, 3)), np.random.randint(0, 10, size=(3, 2))
a1, a2

(array([[1, 9, 1],
        [2, 5, 8],
        [1, 0, 7]]),
 array([[9, 8],
        [9, 0],
        [6, 4]]))

In [26]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)

array([[ 96,  12],
       [111,  48],
       [ 51,  36]])

In [27]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3, a4 = np.random.randint(0, 10, size=(4,3)), np.random.randint(0, 10, size=(4,3))
a3, a3

(array([[6, 7, 1],
        [0, 2, 3],
        [2, 3, 2],
        [5, 5, 4]]),
 array([[6, 7, 1],
        [0, 2, 3],
        [2, 3, 2],
        [5, 5, 4]]))

In [28]:
# Perform a dot product on the two newest arrays you created
a3.dot(a4), a4.dot(a3)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [30]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
a3.T.dot(a4), a4.dot(a3.T)

(array([[33, 74, 63],
        [40, 88, 72],
        [25, 27, 52]]),
 array([[70, 21, 31, 54],
        [ 1,  3,  2,  4],
        [77, 28, 39, 79],
        [41, 31, 30, 61]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [31]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a3, a4

(array([[6, 7, 1],
        [0, 2, 3],
        [2, 3, 2],
        [5, 5, 4]]),
 array([[1, 9, 1],
        [0, 0, 1],
        [6, 5, 6],
        [3, 2, 9]]))

In [32]:
# Compare the two arrays with '>'
a3 > a4

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [33]:
# Compare the two arrays with '>='
a3 >= a4

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [34]:
# Find which elements of the first array are greater than 7
a3 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [35]:
# Which parts of each array are equal? (try using '==')
a3 == a4

array([[False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [42]:
# Sort one of the arrays you just created in ascending order
a3.sort()

In [43]:
a3

array([[1, 6, 7],
       [0, 2, 3],
       [2, 2, 3],
       [4, 5, 5]])

In [40]:
a3[:, ::-1]

array([[7, 6, 1],
       [3, 2, 0],
       [3, 2, 2],
       [5, 5, 4]])

In [44]:
# Sort the indexes of one of the arrays you just created
a3.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [49]:
# Find the index with the maximum value in one of the arrays you've created
a4.argmax()

1

In [50]:
# Find the index with the minimum value in one of the arrays you've created
a4.argmin()

3

In [51]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a4.argmax(axis=1)

array([1, 2, 0, 2])

In [52]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a4.argmin(axis=1)

array([0, 0, 1, 1])

In [55]:
# Create an array of normally distributed random numbers
randn = np.random.randn(2, 4)
randn

array([[ 2.22435038,  0.77169083,  1.90156737, -0.44953665],
       [-1.34587184,  1.49850926, -1.59081242,  0.3391139 ]])

In [64]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.